### ISSUE TITLE
error while running the detect command 

### ISSUE THREAD

**Issue by manasakaringula** [jdidion/atropos#127]
I get a random error while running the detect command. Although few runs are successful. We have ran near to 50 jobs with same inputs on local server to understand the root cause of the issue. Out of 50, 17 failed and others were successful.But a samll note is that it finds the adapters properly, but it generates an error. Could you please help us with the issue .Here is the error -
`2021-06-29 13:29:42,110 INFO: This is Atropos 1.1.29 with Python 3.6.1
2021-06-29 13:29:42,114 INFO: Loading list of known contaminants from file:/data/Atropos_sequencing_adapters.fa
2021-06-29 13:29:42,120 INFO: Detecting adapters and other potential contaminant sequences based on 12-mers in 50000 reads
2021-06-29 13:33:59,145 ERROR: Error executing command: detect
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 217, in execute_cli
    retcode, summary = command.execute(args)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 74, in execute
    self.generate_reports(summary, options)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 154, in generate_reports
    generator.generate_reports(summary)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/reports.py", line 65, in generate_reports
    self.generate_text_report(fmt, summary, outfile, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 21, in generate_text_report
    generate_reports(out, summary, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 33, in generate_reports
    generate_detector_report(outstream, input_idx, n_reads, matches, name)
  File "/usr/local/lib/python3.6/site-packages/atropos-1.1.29-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 66, in generate_detector_report
    ",\n{}".format(' ' * (pad_size + 11)).join(match['known_seqs'])))
TypeError: sequence item 0: expected str instance, tuple found`

**Comment by jdidion** [comment]
@BiocondaBot update

**Comment by jdidion** [comment]
It would be helpful to be able to reproduce this error. Would you be able to share the first 50k reads from one of fastq files/pairs that caused an error?

**Comment by manasakaringula** [comment]
Hi @jdidion, we have used sample "ENCSR356KRQ" from ENCODE. Basically, its an ATAC-seq sample. The detect command fails randomly, when we setup multiple runs on the same sample. It works sometimes and it fails sometimes, although the input and parameter is same. Here I am attaching you the first 50k reads. Any help will be greatly appreciated. I have uploaded both the R1/R2 50k reads. 
[ENCSR356KRQ.zip](https://github.com/jdidion/atropos/files/6937847/ENCSR356KRQ.zip)

**Comment by jdidion** [comment]
Closing as part of a stale issue triage. This issue has been open for 5+ years without recent activity. If this is still relevant, please feel free to reopen or file a new issue.
