### ISSUE TITLE
Error with `detect` adapters

### ISSUE THREAD

**Issue by vmikk** [jdidion/atropos#14]
Hello!
I tried to detect adapter sequences from read sequences with `atropos detect -pe1 r1.fastq -pe2 r2.fastq` and received the following error:

```
2017-05-02 10:52:21,687 INFO: This is Atropos 1.1.2 with Python 3.5.3
2017-05-02 10:52:21,688 INFO: Detecting adapters and other potential contaminant sequences based on 12-mers in 10000 reads
2017-05-02 10:52:21,837 ERROR: Error executing command: detect
Traceback (most recent call last):
  File "/home/mik/miniconda3/envs/ATRO/lib/python3.5/site-packages/atropos/commands/__init__.py", line 199, in execute_cli
    retcode, _ = command.execute(args)
  File "/home/mik/miniconda3/envs/ATRO/lib/python3.5/site-packages/atropos/commands/__init__.py", line 74, in execute
    summary, options.report_file, options.report_formats)
  File "/home/mik/miniconda3/envs/ATRO/lib/python3.5/site-packages/atropos/commands/__init__.py", line 153, in generate_reports
    generator.generate_reports(summary)
  File "/home/mik/miniconda3/envs/ATRO/lib/python3.5/site-packages/atropos/commands/reports.py", line 51, in generate_reports
    self.add_derived_data(summary)
  File "/home/mik/miniconda3/envs/ATRO/lib/python3.5/site-packages/atropos/commands/reports.py", line 66, in add_derived_data
    for bp in summary['total_bp_counts'])
KeyError: 'total_bp_counts'
```
Trimming of adapters worked perfectly with this data.
Atropos was installed in a clean python 3.5 conda environment.

With best regards,
Vladimir

**Comment by jdidion** [comment]
Thanks - working on this today

**Comment by jdidion** [comment]
This is fixed. The 'error' command was also broken and is now fixed. Please install v1.1.4.

**Comment by vmikk** [comment]
Thanks a lot for the fast reply and a new fixed release! It works now!

**Comment by jdidion** [comment]
Great! Please report any other issues you come across.
