### ISSUE TITLE
single read adapter detection does not work

### ISSUE THREAD

**Issue by antonkulaga** [jdidion/atropos#17]
Whenever I try to do this from the latest docker, I get:
```
2017-05-12 18:35:04,245 INFO: Detecting adapters and other potential contaminant sequences based on 12-mers in 10000 reads
2017-05-12 18:35:04,432 ERROR: Error executing command: detect
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 199, in execute_cli
    retcode, _ = command.execute(args)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 74, in execute
    summary, options.report_file, options.report_formats)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 153, in generate_reports
    generator.generate_reports(summary)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/reports.py", line 51, in generate_reports
    self.add_derived_data(summary)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/reports.py", line 66, in add_derived_data
    for bp in summary['total_bp_counts'])
KeyError: 'total_bp_counts'
```

**Comment by jdidion** [comment]
Thanks - I forgot to push a new build after the latest release. It should be fixed now. Pushing new docker builds is now an automated part of the release process.
