### ISSUE TITLE
for many files I get atropos.io.seqio.FormatError: FASTQ file ended prematurely

### ISSUE THREAD

**Issue by antonkulaga** [jdidion/atropos#19]
```
2017-05-12 21:29:40,110 INFO: This is Atropos 0+unknown with Python 3.6.1
2017-05-12 21:29:40,114 INFO: Trimming 0 adapter with at most 10.0% errors in single-end mode ...
2017-05-12 21:48:45,045 ERROR: Atropos error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/util/__init__.py", line 673, in run_interruptible
    func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/base.py", line 22, in __call__
    for batch in command_runner.iterator():
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/base.py", line 266, in __next__
    read_index, record = next(self.iterable)
  File "atropos/io/_seqio.pyx", line 222, in __iter__ (atropos/io/_seqio.c:5280)
atropos.io.seqio.FormatError: FASTQ file ended prematurely
```

**Comment by jdidion** [comment]
That’s strange. Could you do a ‘wc -l’ on the files to make sure the number of lines is a multiple of 4? If so, could you also do ‘tail -4 <file> > filetail.txt’ and upload that?

Thanks

**Comment by antonkulaga** [comment]
Hm. Looks like it is 36914397 and the filetale is
```
+
@@@FDDDFGHFBFIGJGDGGGGGIJJIGEIIGIHIGGEHFGHGIJEHHIGHHHFFFFFFEDCDDDDDBDDDDDEDDDDBBB5<@CCDDDDB<BD<BBDDD
@HWI-ST1155:232:C3E8TACXX:3:1307:11417:70821 1:N:0:TGACCA
AATTAACAGTGCATATAACCAAGTGTTTCCGGAACCGGGATCCGCCTTACACCTTGATTCCCGAGGCCTCGGCGGTGGCGCGGTA
```

**Comment by antonkulaga** [comment]
I suspect it is mine mistake. Will try to redownload the files now...

**Comment by jdidion** [comment]
Yep, looks like a truncated file

**Comment by antonkulaga** [comment]
It was my fault, closing it
