### ISSUE TITLE
UnboundLocalError: local variable 'name3' referenced before assignment

### ISSUE THREAD

**Issue by antonkulaga** [jdidion/atropos#21]
I've tried to build from source (as latest docker release does not contain latest fix with fasta support for atropos detect output. And there I have the following strange error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 199, in execute_cli
    retcode, _ = command.execute(args)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 73, in execute
    self.generate_reports(summary, options)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/__init__.py", line 153, in generate_reports
    generator.generate_reports(summary)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/reports.py", line 65, in generate_reports
    self.generate_text_report(fmt, summary, outfile, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 23, in generate_text_report
    generate_fasta(outfile, summary, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 125, in generate_fasta
    format_match(idx, match, records)
  File "/usr/local/lib/python3.6/site-packages/atropos-0+unknown-py3.6-linux-x86_64.egg/atropos/commands/detect/reports.py", line 119, in format_match
    "{} {}".format(idx, ";".join(name2 + name3)),
UnboundLocalError: local variable 'name3' referenced before assignment
```
The command that I ran was 
```
/usr/local/bin/atropos detect -se ${file} -d heuristic -O fasta
```
where I put real filename instead of ${file} and I used single ended reads

**Comment by jdidion** [comment]
Fixed in 1.1.6
