### ISSUE TITLE
ERROR: Unknown error

### ISSUE THREAD

**Issue by joonlee3** [jdidion/atropos#31]
Hi John,

As you suggested, I attach the error log along with my command line and mini fastq files.

2017-08-05 01:06:56,535 INFO: This is Atropos 1.1.9 with Python 3.6.2
2017-08-05 01:06:56,539 INFO: Loading list of known contaminants from https://raw.githubusercontent.com/jdidion/atropos/master/atropos/adapters/sequencing_adapters.fa
2017-08-05 01:06:56,810 INFO: Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
2017-08-05 01:07:10,720 ERROR: Unknown error
Traceback (most recent call last):
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/util/__init__.py", line 673, in run_interruptible
    func(*args, **kwargs)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/base.py", line 23, in __call__
    self.process_batch(batch)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/base.py", line 58, in process_batch
    self.handle_records(context, records)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/__init__.py", line 48, in handle_records
    super().handle_records(context, records)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/base.py", line 73, in handle_records
    self.handle_record(context, record)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/base.py", line 122, in handle_record
    return self.handle_reads(context, read1, read2)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/__init__.py", line 52, in handle_reads
    return self.record_handler.handle_record(context, read1, read2)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/__init__.py", line 70, in handle_record
    reads = self.modifiers.modify(read1, read2)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/modifiers.py", line 1054, in modify
    read1, read2 = mods(read1, read2)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/modifiers.py", line 401, in __call__
    self.correct_errors(read1, read2, insert_match)
  File "/site/ne/home/i0180769/apps/python/v3.6.2/lib/python3.6/site-packages/atropos/commands/trim/modifiers.py", line 253, in correct_errors
    base2 = BASE_COMPLEMENTS[r2_seq[j]]
IndexError: list index out of range
2017-08-05 01:07:10,731 DEBUG: Not generating report file

**Here is my command line**
ADAPTER_FWD="AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
ADAPTER_REV="AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
atropos --aligner insert -a ${ADAPTER_FWD} -A ${ADAPTER_REV}                            \
--correct-mismatches liberal -q 20 -m 30 --log-file atropos.log --log-level DEBUG \
-o ${fastq_R1_name}.fq.gz -p ${fastq_R2_name}.fq.gz                                                 \
-pe1 ${fastq_R1} -pe2 ${fastq_R2} 
                                    
[temp_1.fastq.gz](https://github.com/jdidion/atropos/files/1202125/temp_1.fastq.gz)
[temp_2.fastq.gz](https://github.com/jdidion/atropos/files/1202124/temp_2.fastq.gz)

**Comment by jdidion** [comment]
That command works for me on your temporary input files.

I thought that the DEBUG output would show what line in the fastq is causing the error, but that's not the case. I'm going to push a new version that has better debugging. Once that's done, I'd appreciate if you could run it again on the complete file so we can pinpoint which line is causing the error.

**Comment by jdidion** [comment]
Version 1.1.10 is now in pypi. Please try again on the full input files and upload the logs. Thanks

**Comment by joonlee3** [comment]
Thanks. I will try it again.

**Comment by jdidion** [comment]
Closing this. Please reopen if the error persists.
