### ISSUE TITLE
miRNA option Error

### ISSUE THREAD

**Issue by mottodora** [jdidion/atropos#39]
When I used miRNA option, I got this error.
In documentation, miRNA option sets the adapter sequence to the Illumina small RNA adapter by default. 
Do I need to specify adapter sequence?
```
atropos trim --mirna -se input.fastq.gz -o output.fastq.gz
2017-09-13 11:39:26,521 INFO: This is Atropos 1.1.12+3.g1d4a9ee with Python 3.6.2
2017-09-13 11:39:26,521 ERROR: Error executing command: trim
Traceback (most recent call last):
  File "/path/to/atropos/atropos/commands/__init__.py", line 217, in execute_cli
    retcode, _ = command.execute(args)
  File "/path/to/atropos/atropos/commands/__init__.py", line 69, in execute
    options = self.parse_args(args)
  File "/path/to/atropos/atropos/commands/__init__.py", line 116, in parse_args
    return parser.parse(args)
  File "/path/to/atropos/atropos/commands/cli.py", line 50, in parse
    self.validate_command_options(options)
  File "/path/to/atropos/atropos/commands/trim/cli.py", line 690, in validate_command_options
    if (options.adapter is None and options.front is None and
AttributeError: 'Namespace' object has no attribute 'adapter'
```

**Comment by mottodora** [comment]
In File "/path/to/atropos/atropos/commands/trim/cli.py", line 690, 
I change `options.adapter is None` to `not hasattr(options, 'adapter')` and it works.

**Comment by jdidion** [comment]
Thanks! This fix will be in the next release.
