### ISSUE TITLE
Add option to configure pysam options when reading SAM/BAM file.

### ISSUE THREAD

**Issue by okartal** [jdidion/atropos#74]
This is the header of my SAM file (BS-seq reads):

@HD     VN:1.0  SO:unknown      GO:query
@PG     ID:pheniqs      PN:pheniqs      CL:pheniqs mux --config analysis/src/conf_multiplex.json --report test.json --output test.sam        VN:2.0.4@RG     ID:ACAGTG       LB:cn1  PU:ACAGTG       SM:At Aj 3
@RG     ID:CGATGT       LB:cn1  PU:CGATGT       SM:At Aj 1@RG     ID:TGACCA       LB:cn1  PU:TGACCA       SM:At Aj 2@RG     ID:undetermined PU:undetermined
700523F:121:CB0L6ANXX:1:1103:1118:2223  77      *       0       0       *       *       0       0       GATGGNAAATTAAATTAAGAGAGGATTTAAATAATAATGATTAATTGTAGAGTTGAGGTAAGTTTTTATTTGATTTTTTAAAGGTTATATGTTTTTTTTAAAATAATTTATTTTTTTATTTTATAT   BABBB#0@0FEGGGGGGG1;1<//:EFDGGGGGEGGGG1?FFGGGG1FF1FGGFGG11?F1@FGGGGGGGGCFFGGGGGF1>:@EGFE<F1FGGGGG<E0<0>;E0<@F0DEF0<C.0=D0C=F68        RG:Z:undetermined       BC:Z:CGTCAA     QT:Z:<>::<B
700523F:121:CB0L6ANXX:1:1103:1118:2223  141     *       0       0       *       *       0       0       ACTTTCCTTTTACTATAATTTTTTAAATTTTATAATCTTTATCTCTTTAATTAATTTTCTTTTACCACTTTTTTTTTCTCATCATTTTCATTCTCACATTTCTAAACATTTTACTATATATTTTCT   BB@BBC;11=@FGGFGGG1;FDGGGGCGGGGFF11FFGGG1E1:1EFDF1=D1CFEGG>GG1=:==11C:FG1/9/E1<11==00<FG>0C0000000=0<@000000<D0000=0:/</00////        RG:Z:undetermined       BC:Z:CGTCAA     QT:Z:<>::<B

(the small hd after the at symbol is a github markdown bug)

When I do
`atropos trim -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --bisulfite truseq --op-order GAWCQ -o test.trimmed1.fastq -p test.trimmed2.fastq --format sam -l test.sam`

I get:
2018-11-16 08:53:04,476 INFO: This is Atropos 1.1.19 with Python 3.6.6
2018-11-16 08:53:04,488 ERROR: Error executing command: trimTraceback (most recent call last):  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/commands/__init__.py", line 217, in execute_cli    retcode, summary = command.execute(args)
  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/commands/__init__.py", line 70, in execute    retcode, summary = self.run_command(options)  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/commands/__init__.py", line 134, in run_command
    runner = runner_class(options)
  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/commands/trim/__init__.py", line 282, in __init__    super().__init__(options, TrimSummary)  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/commands/base.py", line 226, in __init__
    self.iterable = enumerate(reader, 1)
  File "/home/oender/anaconda3/envs/population-epigenetics/lib/python3.6/site-packages/atropos/io/seqio.py", line 559, in __iter__
    return self._iter(pysam.AlignmentFile(self._file))
  File "pysam/libcalignmentfile.pyx", line 734, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 983, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

seems to be related to issue here https://github.com/pysam-developers/pysam/issues/51

**Comment by okartal** [comment]
Thanks @jdidion. Opening with check_sq=False by default makes more sense for unaligned SAM input. Any prediction when this will be available?

**Comment by jdidion** [comment]
I'll do a release next week

**Comment by jdidion** [comment]
1.1.20 is released now. Please try it out.

**Comment by okartal** [comment]
Is this release already in bioconda?

**Comment by jdidion** [comment]
Conda recipe has been updated and PR submitted
